In [ ]:
from src.ft_transformer import CustomerFTTransformer
import pandas as pd

# 1. 定義超參數空間
dropout_values = [0.0, 0.1, 0.2, 0.3, 0.4]
num_attn_blocks_values = [1, 2, 3, 4, 5, 6]

# 2. 用來存放結果
results = []

for dropout in dropout_values:
    for num_attn_blocks in num_attn_blocks_values:
        print(f"Training model with dropout={dropout}, num_attn_blocks={num_attn_blocks}")
        
        # 3. 建立模型
        model = CustomerFTTransformer(num_attn_blocks=num_attn_blocks, dropout=dropout)
        
        # 4. 資料準備與預處理
        model.format_dataframe()
        model.preprocess(use_under_sampling=True, under_sampling_method='tomek')
        model.set_feautres_processed()
        model.set_tablar_dataset()
        model.set_model_config()
        
        # 5. 訓練模型
        model.train_model(num_epochs=500, model_name=f'model_d{dropout}_b{num_attn_blocks}.pth', use_class_weight=True)
        
        # 6. 評估模型（假設會回傳 accuracy 和 cm）
        accuracy, cm = model.evaluate_model(model_name=f'model_d{dropout}_b{num_attn_blocks}.pth')
        
        # 7. 記錄結果
        results.append({
            'dropout': dropout,
            'num_attn_blocks': num_attn_blocks,
            'accuracy': accuracy,
            'cm': cm
        })

# 8. 轉成 DataFrame
df_results = pd.DataFrame(results)

# 9. 找出最佳參數組合
best_row = df_results.loc[df_results['accuracy'].idxmax()]

print("\n===== Best Hyperparameters =====")
print(best_row)

# 10. 輸出所有結果表格（可選）
print("\n===== All Results =====")
print(df_results)

Training model with dropout=0.0, num_attn_blocks=1
Encoded gender: [0, 1]
Encoded primary_diagnosis: [0, 1, 2, 3, 4]
Encoded discharge_to: [0, 1, 2, 3]
=== Feature Encoding Complete ===
Numerical features: ['age', 'num_procedures', 'days_in_hospital', 'comorbidity_score']
Categorical features (encoded): ['gender', 'primary_diagnosis', 'discharge_to']

Sample of encoded data:
  gender primary_diagnosis discharge_to
0      1                 1            1
1      1                 3            0
2      0                 1            2
3      0                 4            0
4      0                 2            3
🔄 Applying under sampling with method: tomek
=== Applying tomek under sampling ===
Original class distribution: {0: 3231, 1: 769}
Imbalance ratio: 4.20
Applying tomek under sampling...
Attempting Tomek Links under sampling...
After Tomek Links: 3646 samples
Removed 354 samples
New class distribution: {0: 2877, 1: 769}
=== Under sampling results ===
Final class distribution: {0: 2

100%|██████████| 3/3 [00:00<00:00, 750.05it/s]

Final train_df_train_csv_processed shape: (3646, 7)
Final test_df_train_csv_processed shape: (1000, 7)
=== END PREPROCESS DEBUG ===
categorical features (cols): ['cat_0', 'cat_1', 'cat_2']
categorical features (array): 3
numerical features (cols): ['num_0', 'num_1', 'num_2', 'num_3']
numerical features (array): 4
🖥️ GPU 可用: NVIDIA GeForce RTX 3060
🔢 可用GPU數量: 1
💾 GPU記憶體: 12.0 GB



c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
c:\Users\ShiShiuan\Desktop\機器學習與人

Using current (post-sampling) data distribution for class weight computation
Current class distribution: {0: 2877, 1: 769}
Class 0: weight = 0.6336
Class 1: weight = 2.3706
Original class distribution (for reference): {0: 3231, 1: 769}
Using class weights: [0.63364613 2.3706112 ]


Model saved as ./models/model_d0.0_b1.pth

=== Training Set Evaluation ===
Training Set Accuracy: 0.9506

Training Set Confusion Matrix:
[[2756  121]
 [  59  710]]
Training Set ROC AUC: 0.9803
✅ 訓練集評估圖表已保存為 'model_d0.0_b1.pth_training_metrics.png'
✅ 模型檔案載入成功: ./models/model_d0.0_b1.pth
✅ 模型架構匹配，直接載入成功


c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\src\ft_transformer.py:846: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\src\ft_transformer.py:947: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded 

Test Accuracy: 0.6150

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.66      0.74       829
           1       0.19      0.39      0.26       171

    accuracy                           0.61      1000
   macro avg       0.52      0.53      0.50      1000
weighted avg       0.73      0.61      0.66      1000


Confusion Matrix:
[[548 281]
 [104  67]]

Detailed Confusion Matrix:
Predicted:       0       1
Actual 0:     548     281
Actual 1:     104      67
混淆矩陣圖表已保存為 'confusion_matrix.png'
Training model with dropout=0.0, num_attn_blocks=2


c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\src\ft_transformer.py:1065: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


Encoded gender: [0, 1]
Encoded primary_diagnosis: [0, 1, 2, 3, 4]
Encoded discharge_to: [0, 1, 2, 3]
=== Feature Encoding Complete ===
Numerical features: ['age', 'num_procedures', 'days_in_hospital', 'comorbidity_score']
Categorical features (encoded): ['gender', 'primary_diagnosis', 'discharge_to']

Sample of encoded data:
  gender primary_diagnosis discharge_to
0      1                 1            1
1      1                 3            0
2      0                 1            2
3      0                 4            0
4      0                 2            3
🔄 Applying under sampling with method: tomek
=== Applying tomek under sampling ===
Original class distribution: {0: 3231, 1: 769}
Imbalance ratio: 4.20
Applying tomek under sampling...
Attempting Tomek Links under sampling...
After Tomek Links: 3646 samples
Removed 354 samples
New class distribution: {0: 2877, 1: 769}
=== Under sampling results ===
Final class distribution: {0: 2877, 1: 769}
Training set size: 4000 -> 3646
Sample

100%|██████████| 3/3 [00:00<00:00, 492.79it/s]
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  wa

Final train_df_train_csv_processed shape: (3646, 7)
Final test_df_train_csv_processed shape: (1000, 7)
=== END PREPROCESS DEBUG ===
categorical features (cols): ['cat_0', 'cat_1', 'cat_2']
categorical features (array): 3
numerical features (cols): ['num_0', 'num_1', 'num_2', 'num_3']
numerical features (array): 4
🖥️ GPU 可用: NVIDIA GeForce RTX 3060
🔢 可用GPU數量: 1
💾 GPU記憶體: 12.0 GB
Using current (post-sampling) data distribution for class weight computation
Current class distribution: {0: 2877, 1: 769}
Class 0: weight = 0.6336
Class 1: weight = 2.3706
Original class distribution (for reference): {0: 3231, 1: 769}
Using class weights: [0.63364613 2.3706112 ]


Model saved as ./models/model_d0.0_b2.pth

=== Training Set Evaluation ===
Training Set Accuracy: 0.9871

Training Set Confusion Matrix:
[[2850   27]
 [  20  749]]
Training Set ROC AUC: 0.9956
✅ 訓練集評估圖表已保存為 'model_d0.0_b2.pth_training_metrics.png'
✅ 模型檔案載入成功: ./models/model_d0.0_b2.pth
✅ 模型架構匹配，直接載入成功


c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\src\ft_transformer.py:846: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\src\ft_transformer.py:947: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded 

Test Accuracy: 0.6420

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.71      0.77       829
           1       0.18      0.32      0.23       171

    accuracy                           0.64      1000
   macro avg       0.51      0.51      0.50      1000
weighted avg       0.72      0.64      0.68      1000


Confusion Matrix:
[[588 241]
 [117  54]]

Detailed Confusion Matrix:
Predicted:       0       1
Actual 0:     588     241
Actual 1:     117      54
混淆矩陣圖表已保存為 'confusion_matrix.png'
Training model with dropout=0.0, num_attn_blocks=3


c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\src\ft_transformer.py:1065: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


Encoded gender: [0, 1]
Encoded primary_diagnosis: [0, 1, 2, 3, 4]
Encoded discharge_to: [0, 1, 2, 3]
=== Feature Encoding Complete ===
Numerical features: ['age', 'num_procedures', 'days_in_hospital', 'comorbidity_score']
Categorical features (encoded): ['gender', 'primary_diagnosis', 'discharge_to']

Sample of encoded data:
  gender primary_diagnosis discharge_to
0      1                 1            1
1      1                 3            0
2      0                 1            2
3      0                 4            0
4      0                 2            3
🔄 Applying under sampling with method: tomek
=== Applying tomek under sampling ===
Original class distribution: {0: 3231, 1: 769}
Imbalance ratio: 4.20
Applying tomek under sampling...
Attempting Tomek Links under sampling...
After Tomek Links: 3646 samples
Removed 354 samples
New class distribution: {0: 2877, 1: 769}
=== Under sampling results ===
Final class distribution: {0: 2877, 1: 769}
Training set size: 4000 -> 3646
Sample

100%|██████████| 3/3 [00:00<00:00, 500.02it/s]
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
c:\Users\ShiShiuan\Desktop\機器學習與人工智慧實作\venv\lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  wa

Final train_df_train_csv_processed shape: (3646, 7)
Final test_df_train_csv_processed shape: (1000, 7)
=== END PREPROCESS DEBUG ===
categorical features (cols): ['cat_0', 'cat_1', 'cat_2']
categorical features (array): 3
numerical features (cols): ['num_0', 'num_1', 'num_2', 'num_3']
numerical features (array): 4
🖥️ GPU 可用: NVIDIA GeForce RTX 3060
🔢 可用GPU數量: 1
💾 GPU記憶體: 12.0 GB
Using current (post-sampling) data distribution for class weight computation
Current class distribution: {0: 2877, 1: 769}
Class 0: weight = 0.6336
Class 1: weight = 2.3706
Original class distribution (for reference): {0: 3231, 1: 769}
Using class weights: [0.63364613 2.3706112 ]


  0%|          | 0/500 [00:00<?, ?it/s]

In [ ]:
df_results